<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:productlist" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:productlist">
    <types>
        <xsd:schema targetNamespace="urn:productlist"
                >
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
        </xsd:schema>
    </types>
    <message name="getProdRequest">
        <part name="category" type="xsd:string" /></message>
    <message name="getProdResponse">
        <part name="return" type="xsd:string" /></message>
    <portType name="productlistPortType">
        <operation name="getProd">
            <documentation>Get a listing of products by category</documentation>
            <input message="tns:getProdRequest"/>
            <output message="tns:getProdResponse"/>
        </operation>
    </portType>
    <binding name="productlistBinding" type="tns:productlistPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getProd">
            <soap:operation soapAction="urn:productlist#getProd" style="rpc"/>
            <input><soap:body use="encoded" namespace="urn:productlist" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
            <output><soap:body use="encoded" namespace="urn:productlist" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
        </operation>
    </binding>
    <service name="productlist">
        <port name="productlistPort" binding="tns:productlistBinding">
            <soap:address location="http://localhost/phpsamplecodes/Concept/SOAP/NuSoap/productlist.php"/>
        </port>
    </service>
</definitions>